# Generated by Django 2.1.11 on 2020-04-02 05:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from ..models import get_token


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser',
                 models.BooleanField(default=False,
                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                     verbose_name='superuser status')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=256)),
                ('mobile_number', models.CharField(blank=True,
                                                   db_index=True, max_length=256, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256)),
                ('avatar', models.CharField(blank=True, max_length=256)),
                ('is_staff', models.BooleanField(default=False)),
                ('token', models.UUIDField(
                    default=get_token, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Group',
                        verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True,
                                        help_text='Specific permissions for this user.',
                                        related_name='user_set',
                                        related_query_name='user',
                                        to='auth.Permission',
                                        verbose_name='user permissions')),
            ],
            options={
                'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'Manage staff.'), ('impersonate_users', 'Impersonate customers.')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                      related_name='profile',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
